#!/usr/bin/env bash

usage() {
    cat <<EOF
usage: ${0##*/} [--help, -*] [containers...]
EOF
}
doc() { 
    usage
    echo 
    cat <<EOF
Creates and submits dq2-get jobs to PBS. One job will be created for 
each container listed. 

The datasets will be downloaded to your working directory. 

Any additional arguments beginning with a '-' will be passed to dq2-get, 
along with the argument that follows. 

For example: 

>>> batchload -f '*.root*' \$(cat list_of_files.txt) 

will submit one job for each dataset in 'list_of_files.txt', only 
downloading root files.  

NOTE: You should only run this in an empty directory where there is room 
to download lots of data! The messy nature of submitting to PBS means your 
working directory may become littered with shell scripts and batch output. 

This is supposed to be stupidly easy to use. If you have questions (or 
better yet, suggestions) ask Dan. 

EOF
}
script_name=dq2batch.sh

test_run=false
while (( $# )) 
do 
    arg=$1
    case $1 in 
	--help )
	    doc
	    exit 1 ;;
	--test )
	    test_run=true 
	    shift;;
	-h) 
	    doc 
	    exit 1 ;;
	-*)
	    dq2_args+=$1" "
	    shift
	    dq2_args+=$1" "
	    shift;; 
	*)
	    files+=$1" "
	    shift;;
    esac
done
if [[ -z $files ]]
    then 
    if [[ ! -t 0 ]]
    then 
	files=$(cat)
    else
	usage
	echo "no containers, quitting..." 1>&2
	exit 1
    fi
fi

if $test_run
    then 
    echo 'files: '
    echo $files
    echo 'dq2-args: '
    (
	set -f 
	echo $dq2_args
    )
fi

if ! command -v voms-proxy-init > /dev/null
then 
    echo "voms-proxy-init not found (did you setup dq2?), quitting..." 1>&2
    exit 1
fi 
if ! $test_run
then
    voms-proxy-init -voms atlas -out local_cert
fi

if [[ $? != 0 ]] 
then 
    echo 'voms failure, quitting...' 1>&2
    exit 1
fi

cat >| $script_name <<EOF
shopt -s expand_aliases

export ATLAS_LOCAL_ROOT_BASE=/home/hep/share/app/atlas/ATLASLocalRootBase
alias setupATLAS='source \${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
setupATLAS --quiet

dq2script=\${ATLAS_LOCAL_ROOT_BASE}/packageSetups/atlasLocalDQ2ClientSetup.sh
alias localSetupDQ2Client='source \${dq2script}'

opts="--skipConfirm --dq2ClientVersion \${dq2ClientVersionVal} --quiet"
localSetupDQ2Client \$opts

echo 'submitted from: ' \$PBS_O_WORKDIR 
cd \$PBS_O_WORKDIR

voms-proxy-init -voms atlas -noregen -q -cert local_cert
(
set -f
EOF


file_array=(${files})

for i in ${!file_array[*]}
do 
    newname=${script_name%.sh}-${i}.sh
    cp $script_name $newname
    echo "dq2-get ${dq2_args} ${file_array[$i]}" >> $newname
    echo ")" >> $newname
    if ! $test_run
    then
	qsub -q hep -l walltime=01:00:00:00 $newname
    fi
done

